/// @file     datatype_hints.hpp
/// @brief    Contains the dataset from datatype_hints.csv
/// @details  Converted by csv2hpp 0.9 on Oct 1, 2026 (see https://github.com/fleschutz/csv2hpp)
///           USAGE: #include "datatype_hints.hpp" ... for (auto& datatype_hint : dataset::datatype_hints) { ...

#pragma once

namespace dataset {

struct datatype_hint_details {
	const char* HINT;                  ///< from column  1 
	const char* DECLARATION;           ///< from column  2 
	const char* TYPE;                  ///< from column  3 
	const char* DESCRIPTION;           ///< from column  4 
};

const datatype_hint_details datatype_hints[] {      // NOTE: 00=empty or unknown field
{"","const char* %s;","TEXT","C/C++ datatype to hold a string when no datatype hint is given"},
{"(bool)","bool %s;","BOOL","C/C++ datatype to hold either true or false"},
{"(byte)","unsigned char %s;","CARD","C/C++ datatype to hold a single byte"},
{"(char)","char %s;","CARD","C/C++ datatype to hold a single character"},
{"(unsigned char)","unsigned char %s;","CARD","C/C++ datatype to hold a single character"},
{"(char[4])","char %s[4];","TEXT","C/C++ datatype to hold 3 characters maximum"},
{"(char[8])","char %s[8];","TEXT","C/C++ datatype to hold 7 characters maximum"},
{"(char[12])","char %s[12];","TEXT","C/C++ datatype to hold 11 characters maximum"},
{"(char[16])","char %s[16];","TEXT","C/C++ datatype to hold 15 characters maximum"},
{"(char[32])","char %s[32];","TEXT","C/C++ datatype to hold 31 characters maximum"},
{"(char[64])","char %s[64];","TEXT","C/C++ datatype to hold 63 characters maximum"},
{"(char[128])","char %s[128];","TEXT","C/C++ datatype to hold 127 characters maximum"},
{"(double)","double %s;","FLOAT","C/C++ datatype for floating point values (mostly 64-bit)"},
{"(float)","float %s;","FLOAT","C/C++ datatype for floating point values (mostly 32-bit)"},
{"(int)","int %s;","CARD","C/C++ datatype for integer values (mostly 32-bit)"},
{"(long double)","long double %s;","CARD","C/C++ datatype for big floating values (mostly 64/128-bit)"},
{"(short)","short %s;","CARD","C/C++ datatype for short integer values (mostly 16-bit)"},
{"(string)","const char* %s;","TEXT","C/C++ datatype to hold a string"},
{"(text)","const char* %s;","TEXT","C/C++ datatype to hold a string"},
{"(std::string)","std::string %s;","TEXT","C++ datatype to hold a string"},
{"(unsigned int)","unsigned int %s;","CARD","C/C++ datatype for unsigned integer values (mostly 32-bit)"},
{"(unsigned short)","unsigned short %s;","CARD","C/C++ datatype for unsigned short integer values (mostly 16-bit)"},
{"(unsigned long)","unsigned long %s;","CARD","C/C++ datatype for unsigned long integer values (mostly 64-bit)"},
{"(unsigned long long)","unsigned long long %s;","CARD","C/C++ datatype for big unsigned integers (mostly 64/128-bit)"},
{"(int8_t)","int8_t %s;","CARD","C/C++ datatype to hold an 8-bit signed integer"},
{"(int16_t)","int16_t %s;","CARD","C/C++ datatype to hold a 16-bit signed integer"},
{"(int32_t)","int32_t %s;","CARD","C/C++ datatype to hold a 32-bit signed integer"},
{"(int64_t)","int64_t %s;","CARD","C/C++ datatype to hold a 64-bit signed integer"},
{"(int128_t)","int128_t %s;","CARD","C/C++ datatype to hold a 128-bit signed integer"},
{"(uint8_t)","uint8_t %s;","CARD","C/C++ datatype to hold an 8-bit unsigned integer"},
{"(uint16_t)","uint16_t %s;","CARD","C/C++ datatype to hold a 16-bit unsigned integer"},
{"(uint32_t)","uint32_t %s;","CARD","C/C++ datatype to hold a 32-bit unsigned integer"},
{"(uint64_t)","uint64_t %s;","CARD","C/C++ datatype to hold a 64-bit unsigned integer"},
{"(uint128_t)","uint128_t %s;","CARD","C/C++ datatype to hold a 128-bit unsigned integer"},
{"(epoch)","uint64_t %s;","EPOCH","C/C++ datatype to hold a UNIX epoch timestamp"},
{"(%)","double %s;","FLOAT","C/C++ datatype to hold a percentage value"},
{"($)","float %s;","FLOAT","C/C++ datatype to hold amount of US Dollars"},
{"(€)","float %s;","FLOAT","C/C++ datatype to hold amount of Euros"},
{"(¥)","float %s;","FLOAT","C/C++ datatype to hold amount of Yens"},
{"(£)","float %s;","FLOAT","C/C++ datatype to hold amount of Pounds"},
{"($/kg)","float %s;","FLOAT","C/C++ datatype to hold amount of US Dollars per kilogram"},
{"(€/kg)","float %s;","FLOAT","C/C++ datatype to hold amount of Euros per kilogram"},
{"(AUD)","float %s;","FLOAT","C/C++ datatype to hold amount of Australian Dollars"},
{"(CNY)","float %s;","FLOAT","C/C++ datatype to hold amount of Yuans"},
{"(EUR)","float %s;","FLOAT","C/C++ datatype to hold amount of Euros"},
{"(GBP)","float %s;","FLOAT","C/C++ datatype to hold amount of Pounds"},
{"(JPY)","float %s;","FLOAT","C/C++ datatype to hold amount of Yens"},
{"(USD)","float %s;","FLOAT","C/C++ datatype to hold amount of US Dollars"},
{"(pm)","SI::length %s;","_pm","Length datatype in picometers for libSI"},
{"(nm)","SI::length %s;","_nm","Length in nanometers for libSI"},
{"(mm)","SI::length %s;","_mm","Length in millimeters for libSI"},
{"(cm)","SI::length %s;","_cm","Length in centimeters for libSI"},
{"(m)","SI::length %s;","_m","Length in meters for libSI"},
{"(km)","SI::length %s;","_km","Length in kilometers for libSI"},
{"(au)","SI::length %s;","_au","Length in astronomical units for libSI"},
{"(pc)","SI::length %s;","_pc","Length in Parsec for libSI"},
{"(ft)","SI::length %s;","_ft","Length in Feet for libSI"},
{"(in)","SI::length %s;","_in","Length in Inch for libSI"},
{"(NM)","SI::length %s;","_NM","Length in nautical miles for libSI"},
{"(Da)","SI::mass %s;","_Da","Mass in daltons for libSI"},
{"(mg)","SI::mass %s;","_mg","Mass in milligrams for libSI"},
{"(g)","SI::mass %s;","_g","Mass in grams for libSI"},
{"(kg)","SI::mass %s;","_kg","Mass in kilograms for libSI"},
{"(t)","SI::mass %s;","_t","Mass in metric tons for libSI"},
{"(ms)","SI::time %s;","_ms","Time in milliseconds for libSI"},
{"(s)","SI::time %s;","_s","Time in seconds for libSI"},
{"(min)","SI::time %s;","_min","Time in minutes for libSI"},
{"(h)","SI::time %s;","_h","Time in hours for libSI"},
{"(days)","SI::time %s;","_days","Time in days for libSI"},
{"(K)","SI::temperature %s;","_K","Temperature in kelvins for libSI"},
{"(degree)","double %s;","FLOAT","C/C++ datatype for angle in degree"},
{"(deg)","double %s;","FLOAT","C/C++ datatype for angle in degree"},
{"(°)","double %s;","FLOAT","C/C++ datatype for angle in degree"},
{"(°C)","SI::temperature %s;","_degC","Temperature in °Celsius for libSI"},
{"(°F)","SI::temperature %s;","_degF","Temperature in °Fahrenheit for libSI"},
{"(bar)","SI::pressure %s;","_bar","Pressure in bar for libSI"},
{"(mbar)","SI::pressure %s;","_mbar","Pressure in millibars for libSI"},
{"(Pa)","SI::pressure %s;","_Pa","Pressure in pascals for libSI"},
{"(hPa)","SI::pressure %s;","_hPa","Pressure in hectopascals for libSI"},
{"(kPa)","SI::pressure %s;","_kPa","Pressure in kilopascals for libSI"},
{"(MPa)","SI::pressure %s;","_MPa","Pressure in megapascals for libSI"},
{"(GPa)","SI::pressure %s;","_GPa","Pressure in gigapascals for libSI"},
{"(mHz)","SI::frequency %s;","_mHz","Frequency in millihertz for libSI"},
{"(Hz)","SI::frequency %s;","_Hz","Frequency in hertz for libSI"},
{"(kHz)","SI::frequency %s;","_kHz","Frequency in kilohertz for libSI"},
{"(MHz)","SI::frequency %s;","_MHz","Frequency in megahertz for libSI"},
{"(GHz)","SI::frequency %s;","_GHz","Frequency in gigahertz for libSI"},
{"(THz)","SI::frequency %s;","_THz","Frequency in terahertz for libSI"},
{"(m/s)","SI::velocity %s;","_m_per_s","Velocity in m/s for libSI"},
{"(km/h)","SI::velocity %s;","_km_per_h","Velocity in km/h for libSI"},
{"(kg/m³)","SI::density %s;","_kg_per_m³","Density in kg/m³ for libSI"},
{"(g/m³)","SI::density %s;","_g_per_m³","Density in g/m³ for libSI"},
{"(mg/m³)","SI::density %s;","_g_per_m³","Density in mg/m³ for libSI"},
{"(m/s²)","SI::acceleration %s;","_m_per_s²","Acceleration in m/s² for libSI"},
{"(kJ/mol)","SI::energy_per_mol %s;","_kJ_per_mol","Energy in kilojoule per mol for libSI"},
{"(km³/s²)","SI::volume_per_time_squared %s;","_km³_per_s²","Volume in km³/s² for libSI"},
}; // (4 columns x 96 rows = 384 cells)

} // end of namespace 'dataset'

