/// @file     datatype_hints.hpp
/// @brief    Contains the dataset from datatype_hints.csv
/// @details  Converted by csv2hpp 0.9 on Oct 1, 2026 (see https://github.com/fleschutz/csv2hpp)
///           USAGE: #include "datatype_hints.hpp" ... for (auto& datatype_hint : dataset::datatype_hints) { ...

#pragma once

namespace dataset {

struct datatype_hint_details {
	const char* HINT;                  ///< from column  1 
	const char* DECLARATION;           ///< from column  2 
	const char* TYPE;                  ///< from column  3 
	const char* DESCRIPTION;           ///< from column  4 
};

const datatype_hint_details datatype_hints[] {      // NOTE: 00=empty or unknown field
{"","const char* %s;","TEXT","C/C++ datatype to hold a string when no datatype hint is given"},
{"(bool)","bool %s;","BOOL","C/C++ datatype to hold either true or false"},
{"(byte)","unsigned char %s;","CARD","C/C++ datatype to hold a single byte"},
{"(char)","char %s;","CARD","C/C++ datatype to hold a single character"},
{"(unsigned char)","unsigned char %s;","CARD","C/C++ datatype to hold a single character"},
{"(char[4])","char %s[4];","TEXT","C/C++ datatype to hold 3 characters maximum"},
{"(char[8])","char %s[8];","TEXT","C/C++ datatype to hold 7 characters maximum"},
{"(char[12])","char %s[12];","TEXT","C/C++ datatype to hold 11 characters maximum"},
{"(char[16])","char %s[16];","TEXT","C/C++ datatype to hold 15 characters maximum"},
{"(char[32])","char %s[32];","TEXT","C/C++ datatype to hold 31 characters maximum"},
{"(char[64])","char %s[64];","TEXT","C/C++ datatype to hold 63 characters maximum"},
{"(char[128])","char %s[128];","TEXT","C/C++ datatype to hold 127 characters maximum"},
{"(double)","double %s;","FLOAT","C/C++ datatype for floating point values (mostly 64-bit)"},
{"(float)","float %s;","FLOAT","C/C++ datatype for floating point values (mostly 32-bit)"},
{"(int)","int %s;","CARD","C/C++ datatype for integer values (mostly 32-bit)"},
{"(long double)","long double %s;","CARD","C/C++ datatype for big floating values (mostly 64/128-bit)"},
{"(short)","short %s;","CARD","C/C++ datatype for short integer values (mostly 16-bit)"},
{"(string)","const char* %s;","TEXT","C/C++ datatype to hold a string"},
{"(text)","const char* %s;","TEXT","C/C++ datatype to hold a string"},
{"(std::string)","std::string %s;","TEXT","C++ datatype to hold a string"},
{"(unsigned int)","unsigned int %s;","CARD","C/C++ datatype for unsigned integer values (mostly 32-bit)"},
{"(unsigned short)","unsigned short %s;","CARD","C/C++ datatype for unsigned short integer values (mostly 16-bit)"},
{"(unsigned long)","unsigned long %s;","CARD","C/C++ datatype for unsigned long integer values (mostly 64-bit)"},
{"(unsigned long long)","unsigned long long %s;","CARD","C/C++ datatype for big unsigned integers (mostly 64/128-bit)"},
{"(int8_t)","int8_t %s;","CARD","C/C++ datatype to hold an 8-bit signed integer"},
{"(int16_t)","int16_t %s;","CARD","C/C++ datatype to hold a 16-bit signed integer"},
{"(int32_t)","int32_t %s;","CARD","C/C++ datatype to hold a 32-bit signed integer"},
{"(int64_t)","int64_t %s;","CARD","C/C++ datatype to hold a 64-bit signed integer"},
{"(int128_t)","int128_t %s;","CARD","C/C++ datatype to hold a 128-bit signed integer"},
{"(uint8_t)","uint8_t %s;","CARD","C/C++ datatype to hold an 8-bit unsigned integer"},
{"(uint16_t)","uint16_t %s;","CARD","C/C++ datatype to hold a 16-bit unsigned integer"},
{"(uint32_t)","uint32_t %s;","CARD","C/C++ datatype to hold a 32-bit unsigned integer"},
{"(uint64_t)","uint64_t %s;","CARD","C/C++ datatype to hold a 64-bit unsigned integer"},
{"(uint128_t)","uint128_t %s;","CARD","C/C++ datatype to hold a 128-bit unsigned integer"},
{"(epoch)","uint64_t %s;","EPOCH","C/C++ datatype to hold a UNIX epoch timestamp"},
{"(%)","double %s;","FLOAT","C/C++ datatype to hold a percentage value"},
{"($)","float %s;","FLOAT","C/C++ datatype to hold amount of US Dollars"},
{"(€)","float %s;","FLOAT","C/C++ datatype to hold amount of Euros"},
{"(¥)","float %s;","FLOAT","C/C++ datatype to hold amount of Yens"},
{"(£)","float %s;","FLOAT","C/C++ datatype to hold amount of Pounds"},
{"($/kg)","float %s;","FLOAT","C/C++ datatype to hold amount of US Dollars per kilogram"},
{"(€/kg)","float %s;","FLOAT","C/C++ datatype to hold amount of Euros per kilogram"},
{"(AUD)","float %s;","FLOAT","C/C++ datatype to hold amount of Australian Dollars"},
{"(CNY)","float %s;","FLOAT","C/C++ datatype to hold amount of Yuans"},
{"(EUR)","float %s;","FLOAT","C/C++ datatype to hold amount of Euros"},
{"(GBP)","float %s;","FLOAT","C/C++ datatype to hold amount of Pounds"},
{"(JPY)","float %s;","FLOAT","C/C++ datatype to hold amount of Yens"},
{"(USD)","float %s;","FLOAT","C/C++ datatype to hold amount of US Dollars"},
{"(pm)","SI::length %s;","_pm","Length in picometers (using libSI)"},
{"(nm)","SI::length %s;","_nm","Length in nanometers (using libSI)"},
{"(mm)","SI::length %s;","_mm","Length in millimeters (using libSI)"},
{"(cm)","SI::length %s;","_cm","Length in centimeters (using libSI)"},
{"(m)","SI::length %s;","_m","Length in meters (using libSI)"},
{"(km)","SI::length %s;","_km","Length in kilometers (using libSI)"},
{"(au)","SI::length %s;","_au","Length in astronomical units (using libSI)"},
{"(pc)","SI::length %s;","_pc","Length in Parsec (using libSI)"},
{"(ft)","SI::length %s;","_ft","Length in Feet (using libSI)"},
{"(in)","SI::length %s;","_in","Length in Inch (using libSI)"},
{"(NM)","SI::length %s;","_NM","Length in nautical miles (using libSI)"},
{"(Da)","SI::mass %s;","_Da","Mass in daltons (using libSI)"},
{"(mg)","SI::mass %s;","_mg","Mass in milligrams (using libSI)"},
{"(g)","SI::mass %s;","_g","Mass in grams (using libSI)"},
{"(kg)","SI::mass %s;","_kg","Mass in kilograms (using libSI)"},
{"(t)","SI::mass %s;","_t","Mass in metric tons (using libSI)"},
{"(ms)","SI::time %s;","_ms","Time in milliseconds (using libSI)"},
{"(s)","SI::time %s;","_s","Time in seconds (using libSI)"},
{"(min)","SI::time %s;","_min","Time in minutes (using libSI)"},
{"(h)","SI::time %s;","_h","Time in hours (using libSI)"},
{"(days)","SI::time %s;","_days","Time in days (using libSI)"},
{"(K)","SI::temperature %s;","_K","Temperature in kelvins (using libSI)"},
{"(degree)","double %s;","FLOAT","C/C++ datatype for angle in degree"},
{"(deg)","double %s;","FLOAT","C/C++ datatype for angle in degree"},
{"(°)","double %s;","FLOAT","C/C++ datatype for angle in degree"},
{"(°C)","SI::temperature %s;","_degC","Temperature in °Celsius (using libSI)"},
{"(°F)","SI::temperature %s;","_degF","Temperature in °Fahrenheit (using libSI)"},
{"(bar)","SI::pressure %s;","_bar","Pressure in bar (using libSI)"},
{"(mbar)","SI::pressure %s;","_mbar","Pressure in millibars (using libSI)"},
{"(Pa)","SI::pressure %s;","_Pa","Pressure in pascals (using libSI)"},
{"(hPa)","SI::pressure %s;","_hPa","Pressure in hectopascals (using libSI)"},
{"(kPa)","SI::pressure %s;","_kPa","Pressure in kilopascals (using libSI)"},
{"(MPa)","SI::pressure %s;","_MPa","Pressure in megapascals (using libSI)"},
{"(GPa)","SI::pressure %s;","_GPa","Pressure in gigapascals (using libSI)"},
{"(mHz)","SI::frequency %s;","_mHz","Frequency in millihertz (using libSI)"},
{"(Hz)","SI::frequency %s;","_Hz","Frequency in hertz (using libSI)"},
{"(kHz)","SI::frequency %s;","_kHz","Frequency in kilohertz (using libSI)"},
{"(MHz)","SI::frequency %s;","_MHz","Frequency in megahertz (using libSI)"},
{"(GHz)","SI::frequency %s;","_GHz","Frequency in gigahertz (using libSI)"},
{"(THz)","SI::frequency %s;","_THz","Frequency in terahertz (using libSI)"},
{"(m/s)","SI::velocity %s;","_m_per_s","Velocity in meters per second (using libSI)"},
{"(km/h)","SI::velocity %s;","_km_per_h","Velocity in kilometer per hour (using libSI)"},
{"(kg/m³)","SI::density %s;","_kg_per_m³","Density in kilograms per cubic meter (using libSI)"},
{"(g/m³)","SI::density %s;","_g_per_m³","Density in grams per cubic meter (using libSI)"},
{"(mg/m³)","SI::density %s;","_g_per_m³","Density in milligrams per cubic meter (using libSI)"},
{"(m/s²)","SI::acceleration %s;","_m_per_s²","Acceleration in meters per square second (using libSI)"},
{"(kJ/mol)","SI::energy_per_mol %s;","_kJ_per_mol","Energy in kilojoule per mol (using libSI)"},
{"(km³/s²)","SI::volume_per_time_squared %s;","_km³_per_s²","Volume in cubic kilometers per second squared (using libSI)"},
}; // (4 columns x 96 rows = 384 cells)

} // end of namespace 'dataset'

